name: Build and push Docker images to AWS ECR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::`date +%F-%I-%M`
    - uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: spring-boot-docker
        region: ${{ secrets.AWS_REGION }}
        tags: ${{ env.RELEASE_VERSION }}
        create_repo: true
