name: Build and push Docker images to DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Login to Docker-Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} 
             -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: docker build -t $REPO:latest .
    - name: Run Docker Image
      run: docker run -d -p 8000:8000 --name $REPO
    - name: Publish Docker image
      run: docker push jainvaibhav02/$REPO:latest
