name: Build and push Docker images to DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker-Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} 
             -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Checkout
      uses: actions/checkout@main
    - name: Build Docker image
      run: docker build -t spring-boot-docker-master:latest .
    - name: Run Docker Image
      run: docker run -d -p 8000:8000 --name spring-boot-docker-master spring-boot-docker-master:latest
    - name: Publish Docker image
      run: docker push jainvaibhav02/testing-docker-github:spring-boot-docker-master
