name: Build and push Docker images to DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Build Docker image
      run: docker build -t spring-boot-docker-master:latest .
    - name: Run Docker Image
      run: |
       docker run -d -p 8080:8080 --name spring-boot-docker-master spring-boot-docker-master:latest
       docker ps
    - name: Publish Docker image
      run: |
       docker logout https://hub.docker.com/repository/docker/jainvaibhav02/testing-docker-github
       docker login https://hub.docker.com/repository/docker/jainvaibhav02/testing-docker-github -u ${{ secrets.DOCKER_USERNAME }} 
             -p ${{ secrets.DOCKER_PASSWORD }}
       docker tag firstimage spring-boot-docker-master:latest
       docker push spring-boot-docker-master:latest
       
